// Generated by scripts/css-types.ts from the stylesheet next to it — do not edit.
declare const styles: {
  readonly active: string;
  readonly body: string;
  readonly bullets: string;
  readonly dot: string;
  readonly dots: string;
  readonly head: string;
  readonly lead: string;
  readonly on: string;
  readonly rules: string;
  readonly stepCount: string;
  readonly tab: string;
  readonly tabs: string;
  readonly terms: string;
  readonly top: string;
  readonly tutorial: string;
};
export default styles;
