import { createElement } from 'react';
import { describe, expect, it } from 'vitest';
import {
  DIFFICULTY_ORDER,
  GENERATOR_VERSION,
  THEME_KEYS,
  dailySeed,
  generatePuzzle,
  makeSeed,
} from '@engine';
import { Dashboard } from '../src/app/features/calendar/Dashboard.js';
import { randomSeed } from '../src/app/features/calendar/randomSeed.js';
import { RESOURCES } from '../src/app/shared/i18n/i18n.js';
import { renderWithI18n } from './support/render.js';

/**
 * A seed carries the generator version. When the generator changes, the same
 * string would describe a different puzzle — so the link is refused rather
 * than reinterpreted (PLAN.md §6.1).
 *
 * The app recognises this from the string *before* the worker, so it does not
 * say "no puzzle could be generated" where nothing was meant to be generated.
 * This is the same expression: a swallowed escape once turned it into a
 * pattern that never matched, and nobody would have noticed — the screen just
 * kept looking as before.
 */
const SEED_VERSION = /^v(\d+)-/;

function versionOf(seed: string): number | undefined {
  const match = SEED_VERSION.exec(seed);
  return match === null ? undefined : Number(match[1]);
}

describe('generator version in the seed', () => {
  it('reads the version from a fresh seed', () => {
    expect(versionOf(makeSeed('garage', 6, 1))).toBe(GENERATOR_VERSION);
  });

  it('recognises an older version as foreign', () => {
    expect(versionOf('v2-garage-6-vl-u8iyn8')).toBe(2);
    expect(versionOf('v2-garage-6-vl-u8iyn8')).not.toBe(GENERATOR_VERSION);
  });

  it('has no opinion on something that is not a seed', () => {
    for (const nonsense of ['', 'garage-6', 'vx-garage-6-vl-abc', 'https://example.com']) {
      expect(versionOf(nonsense), nonsense).toBeUndefined();
    }
  });

  it('is refused by the engine too', () => {
    expect(() => generatePuzzle('v2-garage-6-vl-u8iyn8')).toThrow();
  });
});

describe('daily cases', () => {
  it('carry the current generator version', () => {
    // There used to be a curated catalogue here that had to be regenerated by
    // hand after a version change. Daily cases now come from the date — the
    // promise stays the same: no calendar day leads to a seed the app would
    // refuse right away.
    for (let day = 0; day < 400; day++) {
      const date = new Date(Date.UTC(2026, 0, 1 + day));
      const seed = dailySeed(
        { year: date.getUTCFullYear(), month: date.getUTCMonth() + 1, day: date.getUTCDate() },
        THEME_KEYS,
      );
      expect(versionOf(seed), seed).toBe(GENERATOR_VERSION);
    }
  });

  it('as do drawn cases', () => {
    for (const tier of DIFFICULTY_ORDER) {
      expect(versionOf(randomSeed(tier)), tier).toBe(GENERATOR_VERSION);
    }
  });
});

describe('example in the input field', () => {
  it('names a seed the app accepts', () => {
    // Typed in by hand it said `v1` long after version 2 shipped.
    for (const locale of ['de', 'en'] as const) {
      const markup = renderWithI18n(
        createElement(Dashboard, {
          onOpen: () => undefined,
          onDraw: () => undefined,
          onSettings: () => undefined,
        }),
        locale,
      );
      const example = /placeholder="[^"]*?(v\d+-[a-z]+-\d+-[a-z]+-[a-z0-9]+)/.exec(markup)?.[1];
      expect(example, locale).toBeDefined();
      expect(versionOf(example!), locale).toBe(GENERATOR_VERSION);
    }
  });
});

describe('texts about an old link', () => {
  it('exist in both languages', () => {
    for (const locale of ['de', 'en'] as const) {
      expect(RESOURCES[locale].ui.errors.outdatedSeed.title, locale).toBeTruthy();
      expect(RESOURCES[locale].ui.errors.outdatedSeed.text, locale).toBeTruthy();
    }
  });

  it('do not claim generation failed', () => {
    // The old text said so and was simply wrong. The German counterpart is
    // checked in tests/i18n.test.ts.
    expect(RESOURCES.en.ui.errors.outdatedSeed.title.toLowerCase()).not.toContain('could not');
  });
});
