// Generated by scripts/css-types.ts from the stylesheet next to it — do not edit.
declare const styles: {
  readonly backLabel: string;
  readonly boardArea: string;
  readonly body: string;
  readonly cardList: string;
  readonly game: string;
  readonly globals: string;
  readonly head: string;
  readonly headActions: string;
  readonly headButton: string;
  readonly hintBox: string;
  readonly suspects: string;
  readonly timer: string;
  readonly verdict: string;
};
export default styles;
