// Generated by scripts/css-types.ts from the stylesheet next to it — do not edit.
declare const styles: {
  readonly faded: string;
  readonly panel: string;
  readonly person: string;
  readonly reveal: string;
  readonly role: string;
  readonly seed: string;
  readonly stats: string;
};
export default styles;
