// Generated by scripts/css-types.ts from the stylesheet next to it — do not edit.
declare const styles: {
  readonly badge: string;
  readonly body: string;
  readonly card: string;
  readonly clue: string;
  readonly letter: string;
  readonly name: string;
  readonly placed: string;
  readonly portrait: string;
  readonly selected: string;
  readonly victim: string;
};
export default styles;
