// Generated by scripts/css-types.ts from the stylesheet next to it — do not edit.
declare const styles: {
  readonly active: string;
  readonly confirm: string;
  readonly tool: string;
  readonly toolbar: string;
  readonly tools: string;
};
export default styles;
