// Generated by scripts/css-types.ts from the stylesheet next to it — do not edit.
declare const styles: {
  readonly before: string;
  readonly calendar: string;
  readonly day: string;
  readonly empty: string;
  readonly grid: string;
  readonly head: string;
  readonly headRight: string;
  readonly mark: string;
  readonly number: string;
  readonly solved: string;
  readonly started: string;
  readonly step: string;
  readonly tier: string;
  readonly tierEasy: string;
  readonly tierExpert: string;
  readonly tierHard: string;
  readonly tierMedium: string;
  readonly tierVeryEasy: string;
  readonly today: string;
  readonly weekdays: string;
};
export default styles;
