// Generated by scripts/css-types.ts from the stylesheet next to it — do not edit.
declare const styles: {
  readonly aside: string;
  readonly counter: string;
  readonly dashboard: string;
  readonly done: string;
  readonly head: string;
  readonly headActions: string;
  readonly intro: string;
  readonly seedRow: string;
  readonly tagline: string;
  readonly tier: string;
  readonly tierEasy: string;
  readonly tierExpert: string;
  readonly tierHard: string;
  readonly tierMedium: string;
  readonly tierRow: string;
  readonly tierVeryEasy: string;
  readonly today: string;
};
export default styles;
