// Generated by scripts/css-types.ts from the stylesheet next to it — do not edit.
declare const styles: {
  readonly actions: string;
  readonly overlay: string;
  readonly panel: string;
};
export default styles;
