// Generated by scripts/css-types.ts from the stylesheet next to it — do not edit.
declare const styles: {
  readonly dim: string;
  readonly error: string;
  readonly hintLine: string;
  readonly srOnly: string;
};
export default styles;
