// Generated by scripts/css-types.ts from the stylesheet next to it — do not edit.
declare const styles: {
  readonly panel: string;
  readonly setting: string;
  readonly why: string;
};
export default styles;
