// Generated by scripts/css-types.ts from the stylesheet next to it — do not edit.
declare const styles: {
  readonly details: string;
  readonly inner: string;
  readonly scanner: string;
  readonly status: string;
};
export default styles;
