import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

/**
 * Typed CSS modules.
 *
 * Vite types a CSS module as `Record<string, string>`, so `styles.bord` would
 * compile and render nothing. This writes a declaration next to every
 * `X.module.css` (`X.module.d.css.ts`) listing its real class names — a
 * misspelt class becomes a compile error, as a misspelt i18n key already is.
 *
 * ```bash
 * npm run css:types            # write the declarations
 * npm run css:types -- --check # fail if one is missing or stale (tests do this)
 * ```
 */

const ROOT = join(process.cwd(), 'src');

/** Every `*.module.css` under a directory. */
export function cssModules(directory: string = ROOT): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(directory)) {
    const path = join(directory, entry);
    if (statSync(path).isDirectory()) found.push(...cssModules(path));
    else if (entry.endsWith('.module.css')) found.push(path);
  }
  return found.sort();
}

/** kebab-case to camelCase, as Vite's `localsConvention: 'camelCaseOnly'` does. */
function camelCase(name: string): string {
  return name.replace(/-+(\w)/g, (_, letter: string) => letter.toUpperCase());
}

/** Class names a stylesheet defines, camelCased and sorted. */
export function classNames(css: string): string[] {
  const code = css.replace(/\/\*[\s\S]*?\*\//g, '').replace(/url\([^)]*\)/g, '');
  const names = new Set<string>();
  // A dot after a digit belongs to a number (`0.5`, `1.05rem`); everywhere
  // else — `.a`, `.a.b`, `button.a` — it starts a class name.
  for (const match of code.matchAll(/(?<!\d)\.([a-zA-Z_][\w-]*)/g)) names.add(camelCase(match[1]!));
  return [...names].sort();
}

export function declarationFor(css: string): string {
  const lines = classNames(css).map((name) => `  readonly ${name}: string;`);
  return [
    '// Generated by scripts/css-types.ts from the stylesheet next to it — do not edit.',
    'declare const styles: {',
    ...lines,
    '};',
    'export default styles;',
    '',
  ].join('\n');
}

export function declarationPath(cssPath: string): string {
  return cssPath.replace(/\.module\.css$/, '.module.d.css.ts');
}

if (process.argv[1]?.endsWith('css-types.ts')) {
  const check = process.argv.includes('--check');
  const stale: string[] = [];
  for (const path of cssModules()) {
    const wanted = declarationFor(readFileSync(path, 'utf8'));
    const target = declarationPath(path);
    let existing: string | null = null;
    try {
      existing = readFileSync(target, 'utf8');
    } catch {
      existing = null;
    }
    if (existing === wanted) continue;
    if (check) stale.push(relative(process.cwd(), target).split(sep).join('/'));
    else writeFileSync(target, wanted);
  }
  if (stale.length > 0) {
    console.error('Stale CSS module types — run `npm run css:types`:\n  ' + stale.join('\n  '));
    process.exit(1);
  }
}
